### ISSUE TITLE
Set up linting for this project

### ISSUE THREAD

**Issue by pozil** [salesforce/utam-js-recipes#113]
It would be helpful to set up linting in this project so that we automate things like checking the PO imports.

I can do a PR for this if you're interested. Here's the [UTAM specific config](https://github.com/trailheadapps/ebikes-lwc/blob/main/force-app/test/utam/.eslintrc.json) that I implemented for the E-Bikes sample app.

**Comment by olivier-martin-sf** [comment]
That sounds like a great idea, a PR would be very much appreciated if you have some time!

**Comment by pozil** [comment]
Happy to, I did this in PR #114
