### ISSUE TITLE
[Bug] UTAM extension does not show Available Page Objects

### ISSUE THREAD

**Issue by challme28** [salesforce/utam-js-recipes#120]
### Actual behavior
UTAM extension doesn't show any available page object

- [ ] Unable to compile a Page Object

- [ ] Invalid generated code

- [X] Runtime error

### What is your expected behavior?
The extension shows Page Objects from where to select methods

### Steps to reproduce
I open the Dev Tools and go to the UTAM tab at the end
Try to find available Page Objects

### Environment

- Failing test: It's a private repo

- Node.js: v16.14.2
- OS: IOS
- Browser: Chrome
- Browser Version: latest at the post date

### Additional context
We are trying to validate the existence of a field inside a RecordPage inside a custom Lightning App
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/9601561/216445819-ef63e404-83c2-457b-a6e6-f85c6c15554a.png">

**Comment by jimevans** [comment]
@challme28 Thank you for the report. When you click the `Find Root Page Object` button, what happens?

**Comment by challme28** [comment]
My apologies, I didn't know there was a guide for the extension.
I have followed it and managed to get closer to write my first successful test.

Thanks for the quick response.

I am currently facing an unknown about how to expect a text/label to be present in the UI. I cannot find the right PageObject and methods. It is a custom LWC inside a Lightning Record Page.
<img width="346" alt="image" src="https://user-images.githubusercontent.com/9601561/217375180-f8a8c3e4-21bb-44bd-b982-8e920a9fce12.png">

If there is another channel to where I can take into details on the issue, please let me know.
