### ISSUE TITLE
[Bug] .clickHeaderSpecialLink() not finding tr th:nth-of-type(n) selector

### ISSUE THREAD

**Issue by nebc-jasonfung** [salesforce/utam-js-recipes#121]
### Actual behavior
Navigating to the 1st record in a standard list view datatable and getting the below error:

![image](https://user-images.githubusercontent.com/47176130/216601850-4eb26a07-2ba5-401a-a6f4-5bf9ea2ab189.png)

- [ ] Unable to compile a Page Object
- [ ] Invalid generated code
- [x] Runtime error

### What is your expected behavior?
It should find the special link within a table and proceed to click on it.

![image](https://user-images.githubusercontent.com/47176130/216602309-d7c206c8-2e9d-4a1d-9bee-b69c2881fecd.png)

### Steps to reproduce
Navigate yourself to any list view and attempt to click on the first record using the below code snippet produced by UTAM chrome extension:

`await (await (await (await (await (await utam.load(ConsoleObjectHome)).getListView()).getListViewContainer(ListViewManagerGrid)).getInlineEditGrid()).getTable()).clickHeaderSpecialLink(1);`

or

`await (await (await (await utam.load(ConsoleObjectHome)).getListView()).getListViewContainer(VirtualDataTable)).clickHeaderSpecialLink(1);`

### Environment
- Node.js: v16.13.1
- OS: Mac OS
- Browser: Chrome
- Browser Version: 109.0.0

### Additional context
UTAM chrome extension finds and highlights the special link correctly.

Keen to join the UTAM support slack channel, my email address is: jasonf@nebulaconsulting.co.uk

**Comment by irinash13** [comment]
@nebc-jasonfung , Jason, invite was sent to [jasonf@nebulaconsulting.co.uk](mailto:jasonf@nebulaconsulting.co.uk). Take care from your side and join the channel

**Comment by kartikperumal** [comment]
Hi @nebc-jasonfung It appears the usage could be `getListViewContainer(ListViewManagerPrimaryDisplayManager)).getManagerGrid().getInlineEditGrid()).getTable()).clickHeaderSpecialLink(1);`
However it could be possible I am looking at different page structure. I am happy to assist on slack if you can share the hierarchy/page structure inside the ListViewContainer element.
