### ISSUE TITLE
How to load your custom RecordPage and expect its custom components?

### ISSUE THREAD

**Issue by challme28** [salesforce/utam-js-recipes#123]
### Actual behavior

I'm implementing a custom Record Page with LWC's. Once I've navigated to any record, I want to assert if a text is inside one of my custom LWC. When I load my custom component `BidDetails`, its generated methods don't work properly.

`BidDetails` is a custom component that goes into the header of a Record Page. I want to expect a string value displayed inside the custom component. The `.utam.json` file was generated using the UTAM generator and the pageObjects compiled with the `/utam-preview` config file. However, whenever I tried to load the LWC, I would get a `Element is required` similar error prompt. To solve this I edited the generated file to have the following instead of the `shadow` property.
```
// bidDetails.utam.json
{
  "root": true,
  "selector": {
    "css": "body"
  },
  "elements": [
  ...
}
```

- [ ] Unable to compile a Page Object

- [ ] Invalid generated code

- [X] Runtime error

### What is your expected behavior?
What should I load once I'm on the Record Page? I want to assert the highlighted text
![image](https://user-images.githubusercontent.com/9601561/217614349-bb268e4a-c8c7-4f5c-af24-208f9ef34158.png)

### Steps to reproduce

This is how I'm navigating to the Record Page. Visually, after the click I'm inside the desired Record Page
```
    await (
      await (
        await (
          await (
            await (await utam.load(ObjectHome)).getListView()
          ).getListViewContainer(ListViewManagerGrid)
        ).getInlineEditGrid()
      ).getTable()
    ).clickCellSpecialLink(1);
```
### Environment

- Node.js: v16.14.2
- OS: IOS

**Comment by challme28** [comment]
I cannot find that path. The closest I've gotten is below.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/9601561/218137164-47478004-aff8-4ccb-9550-2ee97caea2d6.png">
<img width="506" alt="image" src="https://user-images.githubusercontent.com/9601561/218138710-97a630c4-1457-43f5-9cf1-3afcf845ae08.png">
<img width="556" alt="image" src="https://user-images.githubusercontent.com/9601561/218137747-6beff93b-2937-430f-9fe3-eb7ca4421142.png">
<img width="555" alt="image" src="https://user-images.githubusercontent.com/9601561/218138156-599c9dbc-bd92-4768-abf8-fba7b2a31bba.png">

This is the root of my RecordPage
<img width="872" alt="image" src="https://user-images.githubusercontent.com/9601561/218140942-8c41b711-6bfe-4bf4-b417-2f9d8aef1838.png">

**Comment by challme28** [comment]
I just got fired from that project.

**Comment by irinash13** [comment]
> I just got fired from that project.

Sorry to hear

**Comment by kartikperumal** [comment]
So sorry to hear. For future reference, the structure looks correct, the only change would have been to use a `getSecondaryFieldContant(YourPageObjectName)` at the end.
