### ISSUE TITLE
[Bug] Issue building project

### ISSUE THREAD

**Issue by Sensiunk** [salesforce/utam-js-recipes#152]
### Actual behavior

`$ yarn generate:utam
yarn run v1.22.5
$ cd utam-generator && yarn generate && yarn compile
$ utam-generate -c generator.config.json
Generating from C:\Users\manjpura\Desktop\UTAM\utam-js-recipes\utam-generator\src\cards\button.html...[DONE]
Generating from C:\Users\manjpura\Desktop\UTAM\utam-js-recipes\utam-generator\src\cards\icon.html...[DONE]
Generating from C:\Users\manjpura\Desktop\UTAM\utam-js-recipes\utam-generator\src\cards\image.html using rules from image.rules.json...[DONE]
Generating from C:\Users\manjpura\Desktop\UTAM\utam-js-recipes\utam-generator\src\cards\text.html...[DONE]
$ utam -c compiler.config.json
Compiling __generated__/button.utam.json... C:\Users\manjpura\Desktop\UTAM\utam-js-recipes\node_modules\utam\build\run_utam.js:209
                    throw new UtamCompilerError(error.toString(entryOptions.entry));
                          ^

UtamCompilerError:
Error in page object __generated__/button.utam.json {"offset":144,"line":7,"column":24}
error 201: element "button": type "utam-lightning/pageObjects\button" is not supported, valid values are: custom, container, frame, actionable, clickable, draggable, editable, touchable;
tip: custom type must only contain alphanumeric characters with the schema [package-name]/[custom/path]/pageObject

    at findAndProcessPOsAndUtils (C:\Users\manjpura\Desktop\UTAM\utam-js-recipes\node_modules\utam\build\run_utam.js:209:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runUtam (C:\Users\manjpura\Desktop\UTAM\utam-js-recipes\node_modules\utam\build\run_utam.js:250:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

- [X] Unable to compile a Page Object

- [ ] Invalid generated code

- [ ] Runtime error

### What is your expected behavior?

Program should build project with no errors and be able to proceed.

### Steps to reproduce
1. Ran yarn install - Worked fine
2. Ran yarn build - This is where it broke

### Environment

- Failing test [e.g force-app/test/record-create.spec.js]

- Node.js: [e.g 14.18.2] v16.20.0
- Yarn: 1.22.5
- OS: [e.g. iOS] Windows_NT x64 10.0.19044
- Browser: [e.g. chrome, safari] VSCode

**Comment by kartikperumal** [comment]
And this is the default button.html with no changes? I will take a look and post an update. Thanks for reporting.

**Comment by Sensiunk** [comment]
No changes were made. I cloned the repo and followed the instructions and got the error on the Build Project step. Thank you for looking into this!

**Comment by olivier-martin-sf** [comment]
May you please run `yarn why utam` at the root of your workspace?

**Comment by Sensiunk** [comment]
I have ran that command and received this output.

`$ yarn why utam
yarn why v1.22.5
[1/4] Why do we have the module "utam"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "utam@2.0.2"
info Reasons this module exists
   - "_project_#wdio-utam-service" depends on it
   - Hoisted from "_project_#wdio-utam-service#utam"
   - Hoisted from "_project_#utam-preview#utam"
info Disk size without dependencies: "152KB"
info Disk size with unique dependencies: "18.46MB"
info Disk size with transitive dependencies: "32.73MB"
info Number of shared dependencies: 40
Done in 1.29s.`

**Comment by irinash13** [comment]
Hi @Sensiunk , what company do you represent?

**Comment by olivier-martin-sf** [comment]
Thanks @Sensiunk, we were able to identify the root cause of your issue (the generator uses a platform specific separator for a module identifier when it should uses a slash) and will publish a new patch release and a PR on that repo that will hopefully fix your issue

**Comment by olivier-martin-sf** [comment]
Hi @Sensiunk, I've opened a PR that uses the latest version of the UTAM JS dependencies in which we fixed the issue that you are encountering. May you please confirm that you can build the project from the branch in #157 ? If so I will go ahead ahead and merge the PR but I would need your approval first as we don't have access to Windows machine within our team

**Comment by Sensiunk** [comment]
Hello @olivier-martin-sf , I've pulled the PR and have verified that it does work on my machine. I appreciate your help in this matter. I will be approving the PR.

**Comment by olivier-martin-sf** [comment]
Thank you for testing the PR and confirming it's fixing the issue @Sensiunk. I've merged the PR so it should available on the main branch now
