### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by cpathipati** [salesforce/utam-js-recipes#16]
**### Actual behavior**
------------------------------------------------------------------
[chrome  mac os x #0-0] Spec: /Users/sf-unified/utam-js-recipes/force-app/test/record-create.spec.js
[chrome  mac os x #0-0] Running: chrome (v) on mac os x
[chrome  mac os x #0-0] Session ID: ec32bc66889e3e30dce609b1d166132c
[chrome  mac os x #0-0]
[chrome  mac os x #0-0] Record creation tests
[chrome  mac os x #0-0]    ✖ "before all" hook
[chrome  mac os x #0-0]    ✖ Create a new Account Record
[chrome  mac os x #0-0]    ✖ Create a new Opportunity Record
[chrome  mac os x #0-0]
[chrome  mac os x #0-0] 3 failing (1.4s)
[chrome  mac os x #0-0]
[chrome  mac os x #0-0] 1) Record creation tests "before all" hook
[chrome  mac os x #0-0] An element on the interface of UTAM Element or a Locator must be provided in order to load a PageObject
[chrome  mac os x #0-0] Error: An element on the interface of UTAM Element or a Locator must be provided in order to load a PageObject
[chrome  mac os x #0-0]     at UtamLoader.load (/Users//sf-unified/utam-js-recipes/node_modules/@utam/loader/build/index.js:42:19)
[chrome  mac os x #0-0]     at login (/Users//sf-unified/utam-js-recipes/force-app/test/utilities/salesforce-test.js:23:30)
[chrome  mac os x #0-0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[chrome  mac os x #0-0]     at UserContext.<anonymous> (/Users//sf-unified/utam-js-recipes/force-app/test/record-create.spec.js:64:9)
[chrome  mac os x #0-0]     at UserContext.executeAsync (/Users//sf-unified/utam-js-recipes/node_modules/@wdio/utils/build/shim.js:101:16)
[chrome  mac os x #0-0]     at UserContext.exports.testFrameworkFnWrapper (/Users//sf-unified/utam-js-recipes/node_modules/@wdio/utils/build/test-framework/testFnWrapper.js:25:18)

**### Steps to reproduce**

Followed the steps as described in the readme file

**### Environment**

Sanbox

**### Additional context**

the Login script seems not working and I think the consequent steps are failing.

**Comment by cpathipati** [comment]
Thanks, Martin

listing steps below

1. I replaced .env file (with my login and credentials)
2. renamed existing pageObject folder to pageObject2
3. ran yarn build, this generated new pageObject folder (just to ensure I have the newly compiled files)
4. Than ran only - yarn test --spec force-app/test/record-create.spec.js
5. got an error with saying (Error: An element on the interface of UTAM Element or a Locator must be provided in order to load a PageObject)

I added try/catch and below is the modified code and error stack. and I also verified the code gets my credentials
added modified utilites/salesforce-test.js

 try{
        const login = await utam.load(Login);
        console.log('after UTAM load');
        await sleep(2000);
    
        await login.login(username, password);
      
        await sleep(2000);
    }catch(e){
        console.log('after UTAM load error');
        console.log(e);
    }
 === error stack

[0-0] Error: An element on the interface of UTAM Element or a Locator must be provided in order to load a PageObject
    at UtamLoader.load (/Users/chandrasekar.pathipa/sf-unified/utam-js-recipes/node_modules/@utam/loader/build/index.js:42:19)
    at login (/Users/chandrasekar.pathipa/sf-unified/utam-js-recipes/force-app/test/utilities/salesforce-test.js:23:34)
    at UserContext.<anonymous> (/Users/chandrasekar.pathipa/sf-unified/utam-js-recipes/force-app/test/record-create.spec.js:67:9)
    at UserContext.executeAsync (/Users/chandrasekar.pathipa/sf-unified/utam-js-recipes/node_modules/@wdio/utils/build/shim.js:101:16)
    at UserContext.exports.testFrameworkFnWrapper (/Users/chandrasekar.pathipa/sf-unified/utam-js-recipes/node_modules/@wdio/utils/build/test-framework/testFnWrapper.js:25:18)
[0-0] 2022-02-07T19:14:40.981Z DEBUG @wdio/utils:shim: Finished to run "afterHook" hook in 0ms

**Comment by olivier-martin-sf** [comment]
I just sent you an invite to join our external support channel where we'll be able to jump in a video call and troubleshoot this. This should help troubleshoot your issue quicker! Hope this works for you.

**Comment by olivier-martin-sf** [comment]
After some analysis, the issue was caused by different versions of the UTAM dependencies being present in the workspace's packages:

- `utam@1.0.1` in the `utam-preview` package
- `wdio-utam-service@1.0.0` at the workspace root

After resetting versions of the dependencies to be in async (to 1.0.1) and running `yarn clean && yarn build && yarn install` we were able to have the test running.

@cpathipati feel free to close the issue to confirm the problem has been solved!

**Comment by cpathipati** [comment]
Thanks, @olivier-martin-sf. This issue is resolved now!
I will continue testing and will let know if any issues.

Thanks again

**Comment by irinash13** [comment]
Thanks a lot, @olivier-martin-sf
