### ISSUE TITLE
[Bug] Tests against Scratch Org only run successfully if the default user navigates to the UTAM Recipes app

### ISSUE THREAD

**Issue by datamike** [salesforce/utam-js-recipes#26]
### Actual behavior
[] Tests are failing
-Errors are in the attached text file.

### What is your expected behavior?
I expected the tests to run successfully.

### Steps to reproduce
- Follow steps under ReadMe.md section: "Run the local app in a scratch org test"
- Open the scratch org in the browser.  (I did not navigate to the UTAM Recipes app)
- Run "yarn test --spec force-app/test/sfdx-scratch-org.spec.js" from terminal.

[UTAM_Test_Output.txt](https://github.com/salesforce/utam-js-recipes/files/8701625/UTAM_Test_Output.txt)

### Environment

- Failing test [e.g force-app/test/record-create.spec.js]
- Node.js: v14.15.5
- OS: OSX
- Browser: Chrome
- Browser Version: Version 101.0.4951.64 

### Additional context
These tests ran successfully after I navigated to the 'UTAM Recipes' app and then re-ran the tests.

**Comment by olivier-martin-sf** [comment]
Thank you for reporting this issue @datamike, before investigating further can you clarify what do you mean by the UTAM Recipes app? Just want to make sure we can reproduce your steps accurately.

**Comment by datamike** [comment]
@olivier-martin-sf  'UTAM Recipes' is the Salesforce Lightning application bundled with the UTAM JS recipes repository - found in directory /force-app/main/default/applications/UTAM_Recipes.app-meta.xml.  I have attached a screenshot taken from my scratch org.

![image](https://user-images.githubusercontent.com/6226438/168814862-9fc50af6-25fb-472c-bf1d-461515fe1a1b.png)

**Comment by olivier-martin-sf** [comment]
Thanks @datamike, I see what you are saying now. So I looked at the terminal logs and it seems that the `appHomePage` variable is `undefined`. Could you confirm that using the 'Debug wdio test' debugger profile? It's unclear to me how navigating to the UTAM Recipes app would change that but some things worth trying:

- make sure you run `yarn generate:login` command and look at the content of the `.env` file at the project root
- try to rebuild the whole project `yarn clean && yarn install && yarn build`

I never navigated to the UTAM Recipes app when trying to execute the tests and got them to work without having to. Let us know how it goes

**Comment by olivier-martin-sf** [comment]
I had the same issue when my **[Org Setup](https://github.com/salesforce/utam-js-recipes#org-setup) was incorrect** @datamike. 

I suggest:

1. double-checking that all steps from that section of the Readme did succeed 
2. make sure you run `yarn generate:login` before trying to run the test.

In this test, we first navigate to the scratch Org homepage URL (URL generated via the `yarn generate:login` script). The homepage should redirects automatically towards the `Hello` LWC component. 

Before executing the test, we wait that the current page URL contains `Hello` in the [`beforeEach` hook](https://github.com/salesforce/utam-js-recipes/blob/main/force-app/test/sfdx-scratch-org.spec.js#L26). It seems that this condition is never satisfied and hence run forever until the tests timeouts. That's the issue you are currently facing. 

If you can look at point 1 and 2 mentioned above, that would be great. Note that you can also run `yarn clean && yarn install && yarn build` to reset the project and make sure it's up to date.

Hope that helps!

**Comment by datamike** [comment]
@olivier-martin-sf Thanks!

1. First, I did _yarn clean && yarn install && yarn build_. .  I had to change my running version of node in order for this to succeed (also had to do this on Monday).  But I did notice something on step 5 of 'yard build' this time that I hadn't noticed before - the message:  "The latest version is "1.22.19", while you're on "1.22.15"." 

➜  utam-js-recipes yarn clean && yarn install && yarn build
yarn run v1.22.15
error utam-js-recipes@0.0.1: The engine "node" is incompatible with this module. Expected version ">=14.15.4 <15". Got "17.6.0"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  utam-js-recipes **nvm use 14.15**                                                            
Now using node v14.15.5 (npm v6.14.11)
➜  utam-js-recipes yarn clean && yarn install && yarn build
yarn run v1.22.15
$ rimraf pageObjects/ node_modules/
✨  Done in 2.13s.
yarn install v1.22.15
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  **Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.22.19", while you're on "1.22.15".**
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
$ husky install
fatal: not a git repository (or any of the parent directories): .git
✨  Done in 8.26s.
yarn run v1.22.15
$ yarn compile:utam && cd utam-preview && yarn compile
$ utam -c utam.config.js
Compiling force-app/main/default/lwc/__utam__/homePage.utam.json... [DONE]
Compiling force-app/main/default/lwc/flexipages/__utam__/appFlexipage.utam.json... [DONE]
Compiling force-app/main/default/lwc/hello/__utam__/hello.utam.json... [DONE]
Compiling force-app/main/default/lwc/wireGetObjectInfo/__utam__/wireGetObjectInfo.utam.json... [DONE]
$ utam -c utam-preview.config.js
Compiling src/portal/dummy.utam.json... [DONE]
Compiling src/portal/nullableExample.utam.json... [DONE]
Compiling src/portal/utamDevHome.utam.json... [DONE]
✨  Done in 1.47s.

2. Then I did _yarn generate:login_  (per the ReadMe file under section "Run the local app in a scratch org test")

This populated the following variable in the .env file:   SCRATCH_ORG_LOGIN_URL=https://some-scratchy-377-dev-ed.cs40.my.salesforce.com/secur/frontdoor.jsp?sid=00D54000000YoEY!AQcAQLfE_ZVsJZLD_0ci_U7p__uapIsny_5_bk6z5swk0IBAX3FDGMI0RiTpTgp5j9f7SwWJ8Mb7XF4tlGSht773sq0K_KLI&retURL=%2Flightning

3. Then I ran _yarn test --spec force-app/test/sfdx-scratch-org.spec.js_

The tests failed again (**_but skip to bullet 4 below because I think I know the reason_**).  
 "spec" Reporter:
------------------------------------------------------------------
[chrome 101.0.4951.64 mac os x #0-0] Spec: /Users/UserX/Dev_Proj/Salesforce/UTAM/utam-js-recipes/force-app/test/sfdx-scratch-org.spec.js
[chrome 101.0.4951.64 mac os x #0-0] Running: chrome (v101.0.4951.64) on mac os x
[chrome 101.0.4951.64 mac os x #0-0] Session ID: 9fa5562a8e34d2a2f235e36be75cd4c4
[chrome 101.0.4951.64 mac os x #0-0]
[chrome 101.0.4951.64 mac os x #0-0] Scratch Org Tests
[chrome 101.0.4951.64 mac os x #0-0]    ✖ hello: displays greeting
[chrome 101.0.4951.64 mac os x #0-0]    ✖ wire: get object info for Contact
[chrome 101.0.4951.64 mac os x #0-0]
[chrome 101.0.4951.64 mac os x #0-0] 2 failing (2m 4.8s)
[chrome 101.0.4951.64 mac os x #0-0]
[chrome 101.0.4951.64 mac os x #0-0] 1) Scratch Org Tests hello: displays greeting
[chrome 101.0.4951.64 mac os x #0-0] Error: Timeout while waiting for condition after 60227ms.
[chrome 101.0.4951.64 mac os x #0-0] Error: Timeout while waiting for condition after 60227ms.
[chrome 101.0.4951.64 mac os x #0-0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[chrome 101.0.4951.64 mac os x #0-0] TypeError: Cannot read property 'getComponent' of undefined
[chrome 101.0.4951.64 mac os x #0-0] TypeError: Cannot read property 'getComponent' of undefined
[chrome 101.0.4951.64 mac os x #0-0]     at UserContext.<anonymous> (/Users/UserX/Dev_Proj/Salesforce/UTAM/utam-js-recipes/force-app/test/sfdx-scratch-org.spec.js:34:46)
[chrome 101.0.4951.64 mac os x #0-0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[chrome 101.0.4951.64 mac os x #0-0]
[chrome 101.0.4951.64 mac os x #0-0] 2) Scratch Org Tests wire: get object info for Contact
[chrome 101.0.4951.64 mac os x #0-0] Error: Timeout while waiting for condition after 60436ms.
[chrome 101.0.4951.64 mac os x #0-0] Error: Timeout while waiting for condition after 60436ms.
[chrome 101.0.4951.64 mac os x #0-0]     at <Jasmine>
[chrome 101.0.4951.64 mac os x #0-0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[chrome 101.0.4951.64 mac os x #0-0] TypeError: Cannot read property 'getNavigationBar' of undefined
[chrome 101.0.4951.64 mac os x #0-0] TypeError: Cannot read property 'getNavigationBar' of undefined
[chrome 101.0.4951.64 mac os x #0-0]     at UserContext.<anonymous> (/Users/UserX/Dev_Proj/Salesforce/UTAM/utam-js-recipes/force-app/test/sfdx-scratch-org.spec.js:44:42)
[chrome 101.0.4951.64 mac os x #0-0]     at <Jasmine>
[chrome 101.0.4951.64 mac os x #0-0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:02:08 

2022-05-18T21:59:17.716Z INFO @wdio/local-runner: Shutting down spawned worker
2022-05-18T21:59:17.967Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-05-18T21:59:17.968Z INFO @wdio/local-runner: shutting down
error Command failed with exit code 1.


4.  I think I now see why it is not working in my scratch org (It's user error on my part).  I did not create a new scratch org per Item 2 under "Org Setup":
>     Create a scratch org and provide it with an alias (utam-js-recipes in the command below):
>.    $ sfdx force:org:create -s -f config/project-scratch-def.json -a utam-js-recipes

I used an existing scratch org which has a different configuration than the provided 'project-scratch-def.json' file.

**Comment by olivier-martin-sf** [comment]
Thanks a lot for your very complete feedback @datamike! Do you confirm that it works as expected when using a scratch org with the correct configuration?

**Comment by olivier-martin-sf** [comment]
That's great news, I will close this issue for now then. Thanks again for your collaboration on this
