### ISSUE TITLE
Getting error on getRecordForm call 

### ISSUE THREAD

**Issue by AparnaPrasannam** [salesforce/utam-js-recipes#41]
### Actual behavior
Configured the project to point against our test environment.
It logs and loads the Account page
Tests passes until selecting New Account
It fails at the getRecordForm
Can't find element with locator 'records-lwc-detail-panel' inside its scope shadow root within timeout 0ms

### What is your expected behavior?
It should return all the items from the recordform and recordlayout calls 

### Steps to reproduce
1.Cloned utam-js-recipes-main 
2.Create .env file for the test environment
3.change the const TEST_ENVIRONMENT_PREFIX = 'sandbox' in the record-create.spec.js and .env file
4.Compile and run the test

**Comment by olivier-martin-sf** [comment]
Hi @AparnaPrasannam, thank you for reporting the issue. 

I will look into it in the next couple of days and see if I can reproduce it in our test environment. Hopefully, I should come back to you by Wednesday.

**Comment by olivier-martin-sf** [comment]
Following up on this, can you provide a screenshot of the record form modal U and the record form modal DOM structure from the devtools 'Elements' panel? Just trying to see if the layout you are using matches or differs the one we used for that recipes repo

**Comment by lizaiv77** [comment]
Closing because of lack of response from the reporting person.

**Comment by divymuni** [comment]
Hi @olivier-martin-sf @lizaiv77 

I'm facing the same issue stated above by @AparnaPrasannam, and I have tried lots of other tricks but no luck. Can you please help me on this asap as I'm stuck here from past 4 days.

attaching the DOM and Record Form screenshot.
![Issue1](https://user-images.githubusercontent.com/75965707/192698445-7d73bc0a-2a5f-40c3-8662-dc94955ee615.PNG)

![image](https://user-images.githubusercontent.com/75965707/192698634-a289853a-4762-4b6b-9a3c-50da1cc03011.png)
