### ISSUE TITLE
[Bug] - salesforce-pageobjects case sensitive error

### ISSUE THREAD

**Issue by chamo7ac** [salesforce/utam-js-recipes#46]
### Actual behavior
Importing module `salesforce-pageobjects/global/pageObjects/recordActionWrapper` cause a module not found error on case sensitive file system (Linux)

- [ ] Unable to compile a Page Object

- [ ] Invalid generated code

- [x] Runtime error

### What is your expected behavior?
All `salesforce-pageobjects` modules to follow the same camel case and case sensitivity convention

### Steps to reproduce
Run test `record-create.spec.js` using `import RecordActionWrapper from 'salesforce-pageobjects/global/pageObjects/recordActionWrapper';` on case sensitive file system.

Error in `Error: cannot find module "node_modules/salesforce-pageobjects/force/pageobjects/changeRecordTypeFooter"` because module is in `salesforce-pageobjects/force/pageObjects/changeRecordTypeFooter` (pageObjects folder instead of pageobjects)

### Environment

- Failing test [e.g force-app/test/record-create.spec.js]

- Node.js: 14.19.3
- OS: Amazon Linux 2
- Browser: chrome
- Browser Version: 103

**Comment by olivier-martin-sf** [comment]
Hi @chamo7ac, thank you for bringing this to our attention. 

That's a good catch!

This is indeed a bug in the `recordActionWrapper.utam.json` page object. We are going to publish a patch release of the `salesforce-pageobjects` package that will fix this issue.

We will keep you updated once it's been published

**Comment by chamo7ac** [comment]
Thank you for this, glad it helps.

**Comment by lizaiv77** [comment]
@chamo7ac fixed in https://www.npmjs.com/package/salesforce-pageobjects/v/1.2.2

**Comment by chamo7ac** [comment]
Confirming issue is fixed in `1.2.2`. Thank you.
