### ISSUE TITLE
Can't find element for Record Form

### ISSUE THREAD

**Issue by divymuni** [salesforce/utam-js-recipes#52]
Hi @olivier-martin-sf @lizaiv77 

I'm facing below issue while retrieving the Record Form
Can't find element with locator 'records-lwc-detail-panel' inside its scope shadow root within timeout 0ms 

I have tried lots of other tricks but no luck. Would be great if you can help me resolve this issue ASAP.

below are the attachments of Record form DOM and Record Form modal.

![Issue1](https://user-images.githubusercontent.com/75965707/192698445-7d73bc0a-2a5f-40c3-8662-dc94955ee615.PNG)

![image](https://user-images.githubusercontent.com/75965707/192698634-a289853a-4762-4b6b-9a3c-50da1cc03011.png)

_Originally posted by @divymuni in https://github.com/salesforce/utam-js-recipes/issues/41#issuecomment-1260422455_

**Comment by olivier-martin-sf** [comment]
Hi @divymuni,

Thank you for taking the time to report the issue you are having. Could you please provide the following information:

- Which version of the Salesforce are you using? 
- Which branch of the project are you on when running your test?
- Which test fail and at which line?
- A more complete stacktrace of the issue you are facing

From there we should have enough information to provide some help!
Looking forward to hear back from you

**Comment by divymuni** [comment]
HI @olivier-martin-sf 

1. Which version of the Salesforce are you using?
-  Winter '23 [Unlimited Edition]

2. Which branch of the project are you on when running your test?
-  Main branch

3. Which test fail and at which line?
-  Path to the file: force-app/test/record-create.spec.js 
   Line no:  41 [ Fatal Error in getRecordForm() function ]
   
4. A more complete stacktrace of the issue you are facing
-  getRecordForm() function is throwing the error which resides in recordActionWrapper.js file of salesforce-pageobjects and
   as you see definition below that getRecordForm() function is calling 3 other functions in it. 

   async getRecordForm() {
        const _statement0 = await this.getDetailPanel();
        const _statement1 = await _statement0.getBaseRecordForm();
        const _result2 = await _statement1.waitForLoad();
        return _result2;
    }
 
  In detailed stacktrace, I've observed that getDetailPanel() has this error. 
 
  async getDetailPanel() {
        const _statement0 = await this.waitFor(async () => {
            const _result0 = await this.getDetailsPanelContainer(_ModalLwcDetailPanelWrapper);
            return _result0;
        });
        const _result1 = await _statement0.getLwcDetailPanel();
        return _result1;
    }

 Above function is returning the value of _result0 but, failed to return the value of _result1 and throwing an error.

 Error: Can't find element with locator 'records-lwc-detail-panel' inside its scope shadow root within timeout 0ms.

 Looking forward to the quick resolution on this, Thanks.

**Comment by olivier-martin-sf** [comment]
Hi @divymuni, I tried to run the test yesterday against our testing environment and I couldn't reproduce the issue you are mentioning. It's likely that your environment differs from the one we use to write our recipes (as stated in the Readme it can differ if there are any customizations). 

Can you open the new Lead (or Account) modal and then open the dev tools console and run the following query to see if it returns something: 

```
$('.oneRecordActionWrapper').querySelector('.actionBody').querySelector(':scope > *:first-child').shadowRoot.querySelector('records-lwc-detail-panel')
```

As you can see in the following image it should return the `records-lwc-detail-panel` custom element, if not you might have to adapt the test to fit your environment. Hope it helps.

<img width="1168" alt="new-account-modal-query" src="https://user-images.githubusercontent.com/77075762/193429104-adeea836-e3c4-4be3-a1ad-a0be84a5a7cc.png">

**Comment by olivier-martin-sf** [comment]
@divymuni pinging you to see if you still are facing this issue?

**Comment by divymuni** [comment]
@olivier-martin-sf Yes, still stuck on the same error.
Result of the query selector is:

![image](https://user-images.githubusercontent.com/75965707/195148844-c8d885a3-de4d-454b-ad06-2bfdbc7735a1.png)

**Comment by olivier-martin-sf** [comment]
Right so it seems that your org has a different layout than the one we use in our testing env which is the reason why the test is failing. This query is reproducing exactly what UTAM is doing to access the `records-lwc-detail-panel`. Now, if you can try  to run the query one step at a time to see which is one is failing (returning `null`) that would be helpful. 

By that I mean, start with `$(.oneRecordActionWrapper)` then `$(.oneRecordActionWrapper).querySelector('.actionBody')` etc until you stumble in the error and let us know which one is failing.

**Comment by olivier-martin-sf** [comment]
@divymuni where you able to nail down the query to see what was failing?

**Comment by divymuni** [comment]
@olivier-martin-sf Attaching snaps of console and located element

![image](https://user-images.githubusercontent.com/75965707/199907281-4db8dd3e-3f3d-4fec-b5f2-0c957e255024.png)

![image](https://user-images.githubusercontent.com/75965707/199907417-8fff9310-c475-450b-b3e9-71e2ec3894a0.png)

Can i please have a quick resolution on this? stuck in a further development.

**Comment by olivier-martin-sf** [comment]
Hi @divymuni, it seems that your page layout is different from the one we used in the recipes (otherwise the query would be successful). 

As the Salesforce platform can be customized in a lot of different ways it makes it impossible for us to provide one-size-fits-all recipes. I would suggest analyzing your DOM structure further and trying to build a query that would match your environment layout which would lead to the new form modal. For instance, I don't know, or can't guess, what's inside the `<div data-aura-rendered-by='2429:0'>`.

On a side note, have you tried our [browser extension](https://utam.dev/tools/browser-extension)? It might help you to investigate which page objects would match certain components of your page. It's a WIP but definitively usable and might help you find which page objects you should be using and how. 

Hope that helps.

**Comment by olivier-martin-sf** [comment]
@divymuni do you still have this issue? Did you try with the latest version of the page objects and the latest Salesforce release?

**Comment by irinash13** [comment]
Closing, no response, assuming the issue is gone
