### ISSUE TITLE
Getting error while loading RecordHomeFlexipage2 to update Record 'Error: Unable to find any valid implementation'

### ISSUE THREAD

**Issue by divymuni** [salesforce/utam-js-recipes#53]
HI @olivier-martin-sf 

### Actual behavior

File path: utam-js-recipes/tree/main/force-app/test/record-update.spec.js

I tried updating a record using above file but execution is failing with the error saying 'Unable to find any valid implementation'.
After debugging the error in detail, I found that 'recordHomeFlexipage2' doesn't have method implementation for getHighlights() method which we're using in test script to access the record highlight panel[Line No: 54 in record-update.spec.js].

FYI,  recordHomeFlexipage2 is an interface.
So, my question is,
How did you utilize below line in your test script to edit/update record? 
Line no: 11 in record-update.spec.js
import RecordHomeFlexipage2 from 'salesforce-pageobjects/global/pageObjects/recordHomeFlexipage2'; 

### What is your expected behavior?
utam-js-recipes/tree/main/force-app/test/record-update.spec.js file should be executed without any error and 
should allow me to edit the record.

### Steps to reproduce
- Clone the main repo & do needful steps provided in Readme file
- Execute this command: yarn test --spec force-app/test/record-update.spec.js
- execution will fail and prompts an error

### Environment

- Failing test: utam-js-recipes/tree/main/force-app/test/record-update.spec.js
- Node.js: 16.17.0
- OS: Windows
- Browser: Chrome
- Browser Version: 105.0.5195.127

### Additional context
![image](https://user-images.githubusercontent.com/75965707/193216533-f1145846-0e7d-47dc-9723-188c9a8a2f37.png)

**Comment by olivier-martin-sf** [comment]
Hi @divymuni,

Indeed, the module `salesforce-pageobjects/global/pageObjects/recordHomeFlexipage2` points to an interface for which the compiler doesn't generate any method implementation. That's the reason why you don't see any method implemented in `salesforce-pageobjects/global/pageObjects/recordHomeFlexipage2`

There's a runtime resolution mechanism that will locate an appropriate implementation for this interface and loads the page object for which the methods are implemented. We have some documentation describing this mechanism here: [interface implementation resolution at runtime](https://utam.dev/grammar/interfaces#interface-implementation-resolution-at-run-time).

For loading the matching interface, there are 2 options:
1. either the page object declares a profile 
2. either the page object doesn't declare a profile and the runtime will load a [default interface](https://utam.dev/grammar/interfaces#default-implementation)

For `salesforce-pageobjects/global/pageObjects/recordHomeFlexipage2` this is option 2 and the default interface is declared in `node_modules/salesforce-pageobjects/dist/ui-utam-pageobjects.config.json` whose content is:

```json
{
    "default": {
        "impl": [
            {
                "interface": "salesforce-pageobjects/global/pageObjects/recordHomeFlexipage2",
                "implementation": "salesforce-pageobjects/global/pageObjects/recordHomeTemplateDesktop"
            }
        ]
    },
    "entity": {
        "lead": [
            {
                "interface": "salesforce-pageobjects/global/pageObjects/recordHomeFlexipage2",
                "implementation": "salesforce-pageobjects/global/pageObjects/recordHomeWithSubheaderTemplateDesktop"
            }
        ]
    }
}
```

So in theory the runtime should load `salesforce-pageobjects/global/pageObjects/recordHomeTemplateDesktop` and if you inspect this page object you will see that the `getHighlights` method is being implemented there:

```js
  /**
   * access highlights panel for Accounts, Contacts, Opportunities. Does NOT work for leads
   * @return highlights panel with record name and summary information
   */
  async getHighlights() {
      const _statement0 = await this.__getDecorator();
      const _statement1 = await _statement0.getEventBroker();
      const _statement2 = await _statement1.waitForTemplate();
      const _statement3 = await _statement2.getGeneratedTemplate(_RecordHomeTemplateDesktop2);
      const _result4 = await _statement3.getHighlights();
      return _result4;
  }
```

It seems like there's something wrong in your setup when trying to locate the matching implementation. I am going to setup my environment to match yours and see if I can reproduce the issue and I will keep you posted.

**Comment by divymuni** [comment]
@olivier-martin-sf #52 is altogether a different issue so I would request you to look into it a & for this issue I will directly load the mentioned Page-objects instead of bothering with the Interface.

I will close this issue once my problem is resolved.
Thanks

**Comment by divymuni** [comment]
Issue is resolved with below changes:

Since, test script wasn't able to retrieve/fetch valid implementation for 'recordHomeFlexipage2', I've directly loaded these two classes: 'recordHomeWithSubheaderTemplateDesktop', 'recordHomeTemplateDesktop'  in my test script using require() to resolve the error.

**Comment by olivier-martin-sf** [comment]
Just FYI, you shouldn't have to do that. I understand it solves your immediate problem but turns out you are just masking something that's off and can lead to bigger problems in the future. 

That being said I haven't tried your node runtime (which might be the culprit) so I am going to see if I hit the same issue with that specific version of Node. I've tried to run the test locally with the node version that's pinned in the package manifest and it works without any issue. 

Also we transpile the test using Babel on the fly so you don't really have to use the `require` function to load your modules and you can use the `import` statement
