### ISSUE TITLE
[Bug] - recordHomeFlexipage2 not implemented

### ISSUE THREAD

**Issue by chamo7ac** [salesforce/utam-js-recipes#70]
### Actual behavior

Error loading page object from "salesforce-pageobjects/global/pageObjects/recordHomeFlexipage2" in `salesforce-pageobjects 2.0.1`

- [ ] Unable to compile a Page Object

- [ ] Invalid generated code

- [x] Runtime error

### What is your expected behavior?

`import Flexipage from "salesforce-pageobjects/global/pageObjects/recordHomeFlexipage2";`
`utam.load(FlexiPage2)` loads page object and its related methods

### Steps to reproduce

`npm install salesforce-pageobjects@2.0.1`

```Javascript
import Flexipage from "salesforce-pageobjects/global/pageObjects/recordHomeFlexipage2";
const flexiPage = await utam.load(Flexipage)
```

Running test containing this statement returns error: `Unable to find any valid implementation`

Looking at the page object, methods are not implemented: 
![image](https://user-images.githubusercontent.com/28420682/196551220-9fffffcc-6ec7-48ea-b2b1-b30f932e0937.png)

### Environment
- Node.js: v14.19
- OS: Linux
- Browser: chrome
- Browser Version: 105

**Comment by olivier-martin-sf** [comment]
Hi @chamo7ac, 

Thanks for reporting this issue. This page object is correct and I've described the behavior in #53.
Do you mind pasting the value of the `services` property in your WDIO config file?

**Comment by chamo7ac** [comment]
Hello, thanks for looking at this and apologies for potential duplicate. As I understand is it a potential issue with the runtime not loading the default `salesforce-pageobjects/global/pageObjects/recordHomeTemplateDesktop` as expected or should I declare the import specifically?
My wdio config is classic with: `services: ["chromedriver", [UtamWdioService, { implicitTimeout: 0 }]]`

**Comment by olivier-martin-sf** [comment]
No worries about the potential duplicate, I was mostly referring to the issue for the detailed explanation. Basically, there's a mechanism build in the UTAM runtime that will automatically pick the right implementation for an interface based on some loaded profiles. Those profiles are defined in some JSON files that are shipped with the package. 

Updating your wdio config to the following should solve your issue:

```js
  // ...wdio.conf.js
  services: ["chromedriver", [UtamWdioService, { implicitTimeout: 0, injectionConfigs: ['salesforce-pageobjects/ui-utam-pageobjects.config.json'] }]]
```

**Comment by chamo7ac** [comment]
Hello, that configuration fixes it, thank you!

**Comment by olivier-martin-sf** [comment]
Thank you for your feedback @chamo7ac! I am glad it worked! Closing this issue as it's been resolved.

**Comment by irinash13** [comment]
Thanks, Olivier!
