### ISSUE TITLE
[Bug] getRelatedList() in path: {salesforce-feature-syntax\node_modules\salesforce-pageobjects\lists\pageObjects\relatedListSingleContainer.js} is not returning accurate result

### ISSUE THREAD

**Issue by divymuni** [salesforce/utam-js-recipes#78]
Hi @olivier-martin-sf @futuremint @mgomes @awaterma @ekashida 

To iterate over the related list, I used function `getRelatedLists()` function that returns the relatedlist elements and inside the for loop I've kept a check that if current element is AuraRelatedList or AppBuilderList.
Check is something like this:
```
if( (await XYZ.getAuraRelatedList) !== null){
continue;
}
```
Issues:

1. Even though the iterated related list is of AuraRelatedList, `getAuraRelatedList()` returning the null instead of returning element thus my check is failing & unable to automate related list functionality. Check my code below:

![image](https://user-images.githubusercontent.com/75965707/200752606-66a9e52e-85a0-4718-b95e-b55dac5c2457.png)

DOM Snapshot:

![Screenshot (342)](https://user-images.githubusercontent.com/75965707/200754495-bb9cce8e-70a0-4070-9583-073bccc1b340.png)

2. Below function is throwing an error that waitForAppBuilderListToLoad() is not a function.  PATH: salesforce-feature-syntax\node_modules\salesforce-pageobjects\dist\lists\utils\relatedListContainerUtils.js

```
async getRelatedList(relatedListName) {
        const _result0 = await _getRelatedList({ pageObject: this }, relatedListName)
        return _result0;
    }
```

**Comment by olivier-martin-sf** [comment]
1. The `auraRelatedList` element is marked as nullable so it can return `null` indeed. We have a [section in our guide](https://utam.dev/guide/presence) documentation that explains how to handle such elements. I am not sure why you are prefixing the `aura` variable with `await` but you shouldn't unless you invoke one of its methods. 

2. Thank you for reporting this issue, I will report that to the team that owns this Page Object extension.

**Comment by kartikperumal** [comment]
Hi @divymuni , I tried to reproduce this for entities with aura related lists and was unsuccessful (getRelatedLists() > getAuraRelatedList()) . Given that there is a new version, could you please try using [v3.0.1 of salesforce-pageobjects](https://www.npmjs.com/package/salesforce-pageobjects) and see if this is still occurring? If this is the case could you provide info on the entities in question? Thank you!

**Comment by irinash13** [comment]
No response, closing
